services:
  - type: web
    name: healthy-skin
    env: node
    plan: free
    buildCommand: npm install && npm --prefix server install && npm run build
    startCommand: cd server && npm start
    autoDeploy: true