import { database } from '../db/connection.js'
import { notify } from './notificationService.js'
import { settleDisputedTransaction } from './walletService.js'

const requireReason=value=>{const reason=String(value||'').trim();if(reason.length<5)throw Object.assign(new Error('Vui lòng nhập lý do ít nhất 5 ký tự.'),{status:422,code:'REASON_REQUIRED'});return reason}
async function audit(client,actorId,action,targetType,targetId,reason,metadata={}){await client.query('insert into admin_audit_logs(actor_id,action,target_type,target_id,reason,metadata) values($1,$2,$3,$4,$5,$6)',[actorId,action,targetType,String(targetId||''),reason,metadata])}
export async function dashboard(){const db=database();if(!db)return {users:0,requests:0,posts:0,sharing:0,transactions:0,openReports:0,openDisputes:0,pendingVerifications:0,grossVnd:0};const {rows}=await db.query(`select
 (select count(*) from users where deleted_at is null) users,
 (select count(*) from requests where deleted_at is null) requests,
 (select count(*) from posts where deleted_at is null) posts,
 (select count(*) from sharing_posts where deleted_at is null) sharing,
 (select count(*) from transactions) transactions,
 (select count(*) from reports where status='open') open_reports,
 (select count(*) from disputes where status='open')+(select count(*) from sharing_access_disputes where status='open') open_disputes,
 (select count(*) from verification_requests where status='pending') pending_verifications,
 (select coalesce(sum(gross_vnd),0) from transactions) gross_vnd`);return rows[0]}
export async function listUsers({q='',status='',role='',page=1}={}){const db=database();if(!db)return {items:[],total:0,page:1};const limit=25,offset=(Math.max(1,Number(page)||1)-1)*limit,values=[],where=[];if(q){values.push(`%${q}%`);where.push(`(u.email ilike $${values.length} or u.display_name ilike $${values.length})`)}if(status){values.push(status);where.push(`u.status=$${values.length}`)}if(role){values.push(role);where.push(`u.role=$${values.length}`)}const clause=where.length?`where ${where.join(' and ')}`:'';values.push(limit,offset);const {rows}=await db.query(`select u.id,u.email,u.display_name,u.real_name,u.role,u.status,u.account_kind,u.created_at,u.updated_at,u.deleted_at,coalesce(w.available_vnd,0) available_vnd,coalesce(w.pending_vnd,0) pending_vnd,count(*) over() total from users u left join wallets w on w.user_id=u.id ${clause} order by u.created_at desc limit $${values.length-1} offset $${values.length}`,values);return {items:rows,total:Number(rows[0]?.total||0),page:Math.max(1,Number(page)||1)}}
export async function updateUser(actor,{id,status,role,reason}){const db=database(),why=requireReason(reason);if(!db)throw Object.assign(new Error('Cần PostgreSQL.'),{status:503});const client=await db.connect();try{await client.query('begin');const target=(await client.query('select * from users where id=$1 for update',[id])).rows[0];if(!target)throw Object.assign(new Error('Không tìm thấy người dùng.'),{status:404});if(target.role==='super_admin'&&actor.role!=='super_admin')throw Object.assign(new Error('Không thể thay đổi quản trị tối cao.'),{status:403});if(role&&actor.role!=='super_admin')throw Object.assign(new Error('Chỉ quản trị tối cao được đổi quyền.'),{status:403});if(role&&!['member','moderator','admin','super_admin'].includes(role))throw Object.assign(new Error('Vai trò không hợp lệ.'),{status:422});if(status&&!['active','suspended','banned'].includes(status))throw Object.assign(new Error('Trạng thái không hợp lệ.'),{status:422});const result=(await client.query('update users set role=coalesce($2,role),status=coalesce($3,status),updated_at=now() where id=$1 returning id,email,display_name,role,status,deleted_at',[id,role||null,status||null])).rows[0];await audit(client,actor.id,'user_update','user',id,why,{before:{role:target.role,status:target.status},after:{role:result.role,status:result.status}});await client.query('commit');await notify(id,{kind:'admin_action',title:'Tài khoản đã được cập nhật',body:`Quản trị viên đã cập nhật tài khoản của bạn. Lý do: ${why}`,actionUrl:'/tai-khoan'});return result}catch(error){await client.query('rollback');throw error}finally{client.release()}}
export async function softDeleteUser(actor,id,reason,restore=false){const db=database(),why=requireReason(reason);const client=await db.connect();try{await client.query('begin');const target=(await client.query('select * from users where id=$1 for update',[id])).rows[0];if(!target)throw Object.assign(new Error('Không tìm thấy người dùng.'),{status:404});if(target.role==='super_admin'&&target.id!==actor.id)throw Object.assign(new Error('Không thể xóa quản trị tối cao khác.'),{status:403});const result=(await client.query(`update users set deleted_at=${restore?'null':'now()'},deleted_by=${restore?'null':'$2'},status=${restore?"'active'":"'suspended'"},updated_at=now() where id=$1 returning id,email,display_name,role,status,deleted_at`,restore?[id]:[id,actor.id])).rows[0];await audit(client,actor.id,restore?'user_restore':'user_soft_delete','user',id,why);if(!restore)await client.query('update sessions set revoked_at=now() where user_id=$1 and revoked_at is null',[id]);await client.query('commit');if(restore)await notify(id,{kind:'admin_action',title:'Tài khoản đã được khôi phục',body:`Lý do: ${why}`,actionUrl:'/tai-khoan'});return result}catch(error){await client.query('rollback');throw error}finally{client.release()}}
const contentConfig={posts:{table:'posts',owner:'author_id',title:'title',status:'moderation_status',deletedStatus:'rejected',restoredStatus:'published'},requests:{table:'requests',owner:'author_id',title:'title',status:'status',deletedStatus:'cancelled',restoredStatus:'open'},sharing:{table:'sharing_posts',owner:'host_id',title:'title',status:'status',deletedStatus:'rejected',restoredStatus:'published'}}
export async function listContent(type,{q='',page=1}={}){const config=contentConfig[type];if(!config)throw Object.assign(new Error('Loại nội dung không hợp lệ.'),{status:422});const db=database(),limit=25,offset=(Math.max(1,Number(page)||1)-1)*limit;const {rows}=await db.query(`select c.id,c.${config.title} title,c.${config.status}::text status,c.created_at,c.deleted_at,u.display_name author_name,u.id author_id,count(*) over() total from ${config.table} c join users u on u.id=c.${config.owner} where ($1='' or coalesce(c.${config.title},'') ilike '%'||$1||'%') order by c.created_at desc limit $2 offset $3`,[q,limit,offset]);return {items:rows,total:Number(rows[0]?.total||0),page:Math.max(1,Number(page)||1)}}
export async function softDeleteContent(actor,type,id,reason,restore=false){const config=contentConfig[type],why=requireReason(reason);if(!config)throw Object.assign(new Error('Loại nội dung không hợp lệ.'),{status:422});const db=database(),client=await db.connect();try{await client.query('begin');const item=(await client.query(`select id,${config.owner} owner_id,${config.title} title,${config.status}::text status from ${config.table} where id=$1 for update`,[id])).rows[0];if(!item)throw Object.assign(new Error('Không tìm thấy nội dung.'),{status:404});await client.query(`update ${config.table} set deleted_at=${restore?'null':'now()'},${config.status}=$2 where id=$1`,[id,restore?config.restoredStatus:config.deletedStatus]);await audit(client,actor.id,restore?'content_restore':'content_soft_delete',type,id,why,{title:item.title,previousStatus:item.status});await client.query('commit');await notify(item.owner_id,{kind:'admin_action',title:restore?'Nội dung đã được khôi phục':'Nội dung đã bị ẩn',body:`${item.title||'Nội dung'} — Lý do: ${why}`});return {id,deleted:!restore}}catch(error){await client.query('rollback');throw error}finally{client.release()}}
export async function listTransactions({status='',page=1}={}){const db=database(),limit=25,offset=(Math.max(1,Number(page)||1)-1)*limit;const {rows}=await db.query(`select t.*,payer.display_name payer_name,payee.display_name payee_name,count(*) over() total from transactions t join users payer on payer.id=t.payer_id left join users payee on payee.id=t.payee_id where ($1='' or t.status::text=$1) order by t.created_at desc limit $2 offset $3`,[status,limit,offset]);return {items:rows,total:Number(rows[0]?.total||0),page:Math.max(1,Number(page)||1)}}
export async function listDisputes(){const db=database();return (await db.query(`select * from (
select d.id,d.transaction_id,'request' kind,d.reason,null::text description,d.status,d.resolution,d.resolved_by,d.created_at,d.resolved_at,t.gross_vnd,t.status transaction_status,u.display_name opened_by_name from disputes d join transactions t on t.id=d.transaction_id join users u on u.id=d.opened_by
union all
select sd.id,sd.transaction_id,'sharing' kind,sd.reason,sd.description,sd.status,sd.resolution,sd.resolved_by,sd.created_at,sd.resolved_at,t.gross_vnd,t.status transaction_status,u.display_name opened_by_name from sharing_access_disputes sd join transactions t on t.id=sd.transaction_id join users u on u.id=sd.buyer_id
) x order by (x.status='open') desc,x.created_at desc limit 100`)).rows}
export async function resolveDispute(actor,id,{resolution,decision}){const why=requireReason(resolution);if(!['refund','release','split','dismiss'].includes(decision))throw Object.assign(new Error('Quyết định tranh chấp không hợp lệ.'),{status:422});const db=database(),client=await db.connect();try{await client.query('begin');let dispute=(await client.query(`select d.*,t.payer_id,t.payee_id,t.gross_vnd,'request' kind from disputes d join transactions t on t.id=d.transaction_id where d.id=$1 for update`,[id])).rows[0];if(!dispute)dispute=(await client.query(`select sd.*,t.payer_id,t.payee_id,t.gross_vnd,'sharing' kind from sharing_access_disputes sd join transactions t on t.id=sd.transaction_id where sd.id=$1 for update`,[id])).rows[0];if(!dispute)throw Object.assign(new Error('Không tìm thấy tranh chấp.'),{status:404});if(dispute.status==='resolved')throw Object.assign(new Error('Tranh chấp đã được xử lý trước đó.'),{status:409});await settleDisputedTransaction(client,dispute.transaction_id,decision);const table=dispute.kind==='request'?'disputes':'sharing_access_disputes';await client.query(`update ${table} set status='resolved',resolution=$2,resolved_by=$3,resolved_at=now() where id=$1`,[id,why,actor.id]);if(dispute.kind==='request')await client.query('insert into dispute_decision_log(dispute_id,stage,reviewer_id,decision) values($1,$2,$3,$4)',[id,'initial',actor.id,{decision,resolution:why}]);await audit(client,actor.id,'dispute_resolve','dispute',id,why,{decision,kind:dispute.kind});await client.query('commit');for(const userId of [dispute.payer_id,dispute.payee_id].filter(Boolean))await notify(userId,{kind:'dispute',title:'Tranh chấp đã được xử lý',body:`Quyết định: ${decision}. ${why}`,actionUrl:'/phien'});return {id,status:'resolved',decision,resolution:why}}catch(error){await client.query('rollback');throw error}finally{client.release()}}
export async function listAudit(){const db=database();return (await db.query(`select a.*,u.display_name actor_name,u.email actor_email from admin_audit_logs a join users u on u.id=a.actor_id order by a.created_at desc limit 200`)).rows}
