import crypto from 'node:crypto'
import jwt from 'jsonwebtoken'
import { OAuth2Client } from 'google-auth-library'
import { database } from '../db/connection.js'
import { env } from '../config/env.js'
const googleClient=new OAuth2Client(env.googleClientId)
const memoryUsers=new Map();const memoryRefresh=new Map()
const hash=value=>crypto.createHash('sha256').update(value).digest('hex')
function issueAccess(user){return jwt.sign({sub:user.id,email:user.email,displayName:user.display_name},env.jwtSecret,{expiresIn:'15m',issuer:'tlucs-api',audience:'tlucs-app'})}
async function issueSession(user,meta={}){const refreshToken=crypto.randomBytes(48).toString('base64url');const refreshHash=hash(refreshToken);const expiresAt=new Date(Date.now()+30*86400000);const db=database();if(db)await db.query('insert into sessions(user_id,refresh_token_hash,user_agent,ip_address,expires_at) values($1,$2,$3,$4,$5)',[user.id,refreshHash,meta.userAgent||null,meta.ip||null,expiresAt]);else memoryRefresh.set(refreshHash,{userId:user.id,expiresAt});return {accessToken:issueAccess(user),refreshToken,expiresAt}}
async function upsertGoogleUser(profile){const db=database();if(!db){let user=[...memoryUsers.values()].find(x=>x.email===profile.email);if(!user){user={id:crypto.randomUUID(),email:profile.email,real_name:profile.name,display_name:profile.name,avatar_url:profile.picture,account_kind:'explorer',onboarding_completed:false};memoryUsers.set(user.id,user)}return user}const {rows}=await db.query(`with existing as (select user_id from auth_accounts where provider='google' and provider_account_id=$1), inserted as (insert into users(email,real_name,display_name,avatar_url) select $2,$3,$3,$4 where not exists(select 1 from existing) on conflict(email) do update set avatar_url=coalesce(excluded.avatar_url,users.avatar_url) returning id) insert into auth_accounts(user_id,provider,provider_account_id,provider_email) select coalesce((select user_id from existing),(select id from inserted)),'google',$1,$2 on conflict(provider,provider_account_id) do update set provider_email=excluded.provider_email returning user_id`,[profile.sub,profile.email,profile.name,profile.picture]);const result=await db.query('select * from users where id=$1',[rows[0].user_id]);return result.rows[0]}
export async function loginWithGoogle(credential,meta){if(!env.googleClientId)throw Object.assign(new Error('Google OAuth chưa được cấu hình.'),{status:503,code:'GOOGLE_AUTH_NOT_CONFIGURED'});const ticket=await googleClient.verifyIdToken({idToken:credential,audience:env.googleClientId});const payload=ticket.getPayload();if(!payload?.email_verified)throw Object.assign(new Error('Email Google chưa được xác minh.'),{status:401,code:'GOOGLE_EMAIL_UNVERIFIED'});const user=await upsertGoogleUser(payload);return {user,session:await issueSession(user,meta)}}
export async function loginDev(meta){if(env.nodeEnv==='production')throw Object.assign(new Error('Không khả dụng.'),{status:404});const user=await upsertGoogleUser({sub:'tlucs-demo-user',email:'demo@tlucs.local',name:'Sinh viên Demo',picture:null});return {user,session:await issueSession(user,meta)}}
export async function refreshSession(refreshToken){const tokenHash=hash(refreshToken||'');const db=database();let user;if(db){const {rows}=await db.query(`select u.* from sessions s join users u on u.id=s.user_id where s.refresh_token_hash=$1 and s.revoked_at is null and s.expires_at>now()`,[tokenHash]);user=rows[0]}else{const session=memoryRefresh.get(tokenHash);if(session&&session.expiresAt>new Date())user=memoryUsers.get(session.userId)}if(!user)throw Object.assign(new Error('Refresh token không hợp lệ.'),{status:401,code:'INVALID_REFRESH_TOKEN'});return {accessToken:issueAccess(user),user}}
export async function getUser(userId){const db=database();if(!db)return memoryUsers.get(userId);const [user,memberships,topics,availability]=await Promise.all([db.query('select * from users where id=$1',[userId]),db.query(`select um.*,u.code university_code,u.name university_name from university_memberships um join universities u on u.id=um.university_id where um.user_id=$1 order by (um.verification_status='approved') desc,u.name`,[userId]),db.query('select topic_id from user_topics where user_id=$1',[userId]),db.query('select weekday,start_time,end_time,timezone from user_availability where user_id=$1 order by weekday,start_time',[userId])]);return user.rows[0]?{...user.rows[0],memberships:memberships.rows,topic_ids:topics.rows.map(x=>x.topic_id),availability:availability.rows}:null}
export async function completeOnboarding(userId,input){const db=database();if(!db){const user=memoryUsers.get(userId);Object.assign(user,{display_name:input.displayName,account_kind:input.accountKind,area_label:input.areaLabel,default_university_id:input.defaultUniversityId||null,onboarding_completed:true,topics:input.topicIds,availability:input.availability,memberships:input.defaultUniversityId?[{university_id:input.defaultUniversityId,relation:input.accountKind==='alumni'?'alumni':'student',verification_status:null}]:[]});return user}const client=await db.connect();try{await client.query('begin');const {rows}=await client.query('update users set display_name=$2,account_kind=$3,default_university_id=$4,area_label=$5,onboarding_completed=true,updated_at=now() where id=$1 returning *',[userId,input.displayName,input.accountKind,input.defaultUniversityId||null,input.areaLabel]);if(input.defaultUniversityId)await client.query('insert into university_memberships(user_id,university_id,relation) values($1,$2,$3) on conflict(user_id,university_id) do update set relation=excluded.relation',[userId,input.defaultUniversityId,input.accountKind==='alumni'?'alumni':'student']);await client.query('delete from user_topics where user_id=$1',[userId]);for(const topicId of input.topicIds)await client.query('insert into user_topics(user_id,topic_id) values($1,$2)',[userId,topicId]);await client.query('delete from user_availability where user_id=$1',[userId]);for(const slot of input.availability)await client.query('insert into user_availability(user_id,weekday,start_time,end_time) values($1,$2,$3,$4)',[userId,slot.weekday,slot.startTime,slot.endTime]);await client.query('insert into user_preferences(user_id,active_university_id) values($1,$2) on conflict(user_id) do update set active_university_id=excluded.active_university_id,updated_at=now()',[userId,input.defaultUniversityId||null]);await client.query('commit');return {...rows[0],memberships:input.defaultUniversityId?[{university_id:input.defaultUniversityId,relation:input.accountKind==='alumni'?'alumni':'student',verification_status:null}]:[]}}catch(error){await client.query('rollback');throw error}finally{client.release()}}
