import crypto from 'node:crypto'
import { EventEmitter } from 'node:events'
import { database } from '../db/connection.js'
const rooms=new Map();const messages=[]
export const conversationEvents=new EventEmitter()
export async function createRequestConversation({requestId,authorId,receiverId,client=null}){if(!client){const conversation={id:crypto.randomUUID(),kind:'request',request_id:requestId,members:[authorId,receiverId].filter(Boolean),created_at:new Date().toISOString()};rooms.set(conversation.id,conversation);return conversation}const conversation=(await client.query(`insert into conversations(kind,request_id) values('request',$1) returning *`,[requestId])).rows[0];for(const userId of [authorId,receiverId])await client.query('insert into conversation_members(conversation_id,user_id) values($1,$2)',[conversation.id,userId]);return conversation}
export async function createSharingConversation({hostId,client=null}){if(!client){const conversation={id:crypto.randomUUID(),kind:'sharing',members:[hostId],created_at:new Date().toISOString()};rooms.set(conversation.id,conversation);return conversation}const conversation=(await client.query(`insert into conversations(kind) values('sharing') returning *`)).rows[0];await client.query('insert into conversation_members(conversation_id,user_id) values($1,$2)',[conversation.id,hostId]);return conversation}
export async function createDirectConversation({userIds,client=null}){if(!client){const conversation={id:crypto.randomUUID(),kind:'direct',members:[...new Set(userIds)],created_at:new Date().toISOString()};rooms.set(conversation.id,conversation);return conversation}const conversation=(await client.query(`insert into conversations(kind) values('direct') returning *`)).rows[0];for(const userId of new Set(userIds))await client.query('insert into conversation_members(conversation_id,user_id) values($1,$2)',[conversation.id,userId]);return conversation}
export async function addConversationMember({conversationId,userId,client=null}){if(!client){const room=rooms.get(conversationId);if(room&&!room.members.includes(userId))room.members.push(userId);return}await client.query('insert into conversation_members(conversation_id,user_id) values($1,$2) on conflict do nothing',[conversationId,userId])}
export async function listConversations(userId){const db=database();if(!db)return [...rooms.values()].filter(x=>x.members.includes(userId)).map(room=>({...room,last_message:messages.find(x=>x.conversation_id===room.id)||null}));const {rows}=await db.query(`select c.*,r.title request_title,(select row_to_json(m) from messages m where m.conversation_id=c.id order by m.created_at desc limit 1) last_message from conversations c join conversation_members cm on cm.conversation_id=c.id left join requests r on r.id=c.request_id where cm.user_id=$1 order by coalesce((select max(created_at) from messages where conversation_id=c.id),c.created_at) desc`,[userId]);return rows}
async function assertMember(db,userId,conversationId){if(!db){const room=rooms.get(conversationId);if(!room?.members.includes(userId))throw Object.assign(new Error('Bạn không thuộc cuộc trò chuyện này.'),{status:403});return room}const result=await db.query('select 1 from conversation_members where conversation_id=$1 and user_id=$2',[conversationId,userId]);if(!result.rowCount)throw Object.assign(new Error('Bạn không thuộc cuộc trò chuyện này.'),{status:403})}
export async function listMessages(userId,conversationId,before){const db=database();await assertMember(db,userId,conversationId);if(!db)return messages.filter(x=>x.conversation_id===conversationId&&(!before||x.created_at<before)).slice(-50);const values=[conversationId];let clause='';if(before){values.push(before);clause=`and created_at < $2`}const {rows}=await db.query(`select * from messages where conversation_id=$1 ${clause} order by created_at desc limit 50`,values);return rows.reverse()}
export async function sendMessage(userId,conversationId,input){const body=typeof input.body==='string'?input.body.trim():'';const kind=input.kind||'text';if(!['text','image','file','audio'].includes(kind))throw Object.assign(new Error('Loại tin nhắn không hợp lệ.'),{status:422});if(kind==='text'&&(body.length<1||body.length>4000))throw Object.assign(new Error('Tin nhắn cần từ 1 đến 4.000 ký tự.'),{status:422});const db=database();await assertMember(db,userId,conversationId);let message;if(!db){message={id:crypto.randomUUID(),conversation_id:conversationId,sender_id:userId,kind,body:body||null,attachment_url:input.attachmentUrl||null,created_at:new Date().toISOString()};messages.push(message)}else message=(await db.query('insert into messages(conversation_id,sender_id,kind,body,attachment_url) values($1,$2,$3,$4,$5) returning *',[conversationId,userId,kind,body||null,input.attachmentUrl||null])).rows[0];conversationEvents.emit('message',message);return message}
export async function canAccessConversation(userId,conversationId){try{await assertMember(database(),userId,conversationId);return true}catch{return false}}
