import crypto from 'node:crypto'
import { database } from '../db/connection.js'
import { createDirectConversation } from './conversationService.js'
const peers=[{id:'peer-minh-anh',display_name:'Nguyễn Minh Anh',account_kind:'university_student',university_code:'HCMUS',average_rating:4.9,completed_requests:32},{id:'peer-gia-huy',display_name:'Trần Gia Huy',account_kind:'university_student',university_code:'HCMUS',average_rating:4.8,completed_requests:19},{id:'peer-khanh-linh',display_name:'Lê Khánh Linh',account_kind:'university_student',university_code:'HCMUS',average_rating:5,completed_requests:27}]
const chatRequests=[],blocks=[]
export async function listPeople(userId,{q='',universityId}={}){const db=database();if(!db)return peers.filter(x=>!q||x.display_name.toLowerCase().includes(q.toLowerCase()));const values=[userId],where=[`u.id<>$1`,`u.status='active'`,`not exists(select 1 from user_blocks b where b.blocker_id=$1 and b.blocked_id=u.id)`];if(universityId){values.push(universityId);where.push(`um.university_id=$${values.length}`)}if(q){values.push(`%${q}%`);where.push(`u.display_name ilike $${values.length}`)}return (await db.query(`select u.id,u.display_name,u.avatar_url,u.account_kind,uni.code university_code,um.verification_status,rs.average_rating,rs.completed_requests from users u left join university_memberships um on um.user_id=u.id left join universities uni on uni.id=um.university_id left join user_reputation_stats rs on rs.user_id=u.id where ${where.join(' and ')} order by (um.verification_status='approved') desc,rs.completed_requests desc nulls last limit 50`,values)).rows}
export async function requestChat(senderId,recipientId,introMessage){const intro=String(introMessage||'').trim();if(senderId===recipientId||intro.length<5||intro.length>300)throw Object.assign(new Error('Lời mời trò chuyện cần từ 5 đến 300 ký tự.'),{status:422});const db=database();if(!db){if(blocks.some(x=>x.blocker_id===recipientId&&x.blocked_id===senderId))throw Object.assign(new Error('Không thể gửi lời mời tới tài khoản này.'),{status:403});const item={id:crypto.randomUUID(),sender_id:senderId,recipient_id:recipientId,intro_message:intro,status:'pending',created_at:new Date().toISOString()};chatRequests.push(item);return item}const blocked=await db.query('select 1 from user_blocks where blocker_id=$1 and blocked_id=$2',[recipientId,senderId]);if(blocked.rowCount)throw Object.assign(new Error('Không thể gửi lời mời tới tài khoản này.'),{status:403});return (await db.query('insert into conversation_requests(sender_id,recipient_id,intro_message) values($1,$2,$3) returning *',[senderId,recipientId,intro])).rows[0]}
export async function listChatRequests(userId){const db=database();if(!db)return chatRequests.filter(x=>x.recipient_id===userId&&x.status==='pending');return (await db.query(`select cr.*,u.display_name,u.avatar_url from conversation_requests cr join users u on u.id=cr.sender_id where cr.recipient_id=$1 and cr.status='pending' order by cr.created_at desc`,[userId])).rows}
export async function respondChatRequest(userId,id,decision){if(!['accepted','declined'].includes(decision))throw Object.assign(new Error('Phản hồi không hợp lệ.'),{status:422});const db=database();if(!db){const item=chatRequests.find(x=>x.id===id&&x.recipient_id===userId&&x.status==='pending');if(!item)throw Object.assign(new Error('Lời mời không còn khả dụng.'),{status:409});item.status=decision;return {request:item,conversation:decision==='accepted'?await createDirectConversation({userIds:[item.sender_id,userId]}):null}}const client=await db.connect();try{await client.query('begin');const item=(await client.query('update conversation_requests set status=$3,responded_at=now() where id=$1 and recipient_id=$2 and status=\'pending\' returning *',[id,userId,decision])).rows[0];if(!item)throw Object.assign(new Error('Lời mời không còn khả dụng.'),{status:409});const conversation=decision==='accepted'?await createDirectConversation({userIds:[item.sender_id,userId],client}):null;await client.query('commit');return {request:item,conversation}}catch(error){await client.query('rollback');throw error}finally{client.release()}}
export async function blockUser(userId,blockedId){if(userId===blockedId)throw Object.assign(new Error('Không thể tự chặn chính mình.'),{status:422});const db=database();if(!db){if(!blocks.some(x=>x.blocker_id===userId&&x.blocked_id===blockedId))blocks.push({blocker_id:userId,blocked_id:blockedId});return {active:true}}await db.query('insert into user_blocks(blocker_id,blocked_id) values($1,$2) on conflict do nothing',[userId,blockedId]);await db.query(`update conversation_requests set status='cancelled',responded_at=now() where status='pending' and ((sender_id=$1 and recipient_id=$2) or (sender_id=$2 and recipient_id=$1))`,[userId,blockedId]);return {active:true}}
