import { Route,Routes } from 'react-router-dom'
import NavBar from './components/NavBar';import Footer from './components/Footer';import PaymentSimulationOverlay from './components/PaymentSimulationOverlay';import AiChatbot from './components/AiChatbot'
import HomePage from './pages/HomePage';import MarketplacePage from './pages/MarketplacePage';import PeersPage from './pages/PeersPage';import CreateRequestPage from './pages/CreateRequestPage'
import LoginPage from './pages/LoginPage';import RegisterPage from './pages/RegisterPage';import SharingBoardPage from './pages/SharingBoardPage';import ForumPage from './pages/ForumPage';import SchoolServersPage from './pages/SchoolServersPage';import MessagesPage from './pages/MessagesPage'
import WalletPage from './pages/WalletPage';import SessionsPage from './pages/SessionsPage';import AccountPage from './pages/AccountPage';import AdminPage from './pages/AdminPage';import SearchPage from './pages/SearchPage';import NotificationsPage from './pages/NotificationsPage';import MySharingPage from './pages/MySharingPage';import MyRequestsPage from './pages/MyRequestsPage'

export default function App(){return <div className="min-h-screen bg-[#fbfcff] text-[#14213d]"><NavBar/><PaymentSimulationOverlay/><main><Routes>
  <Route path="/" element={<HomePage/>}/><Route path="/tim-kiem" element={<SearchPage/>}/><Route path="/thong-bao" element={<NotificationsPage/>}/><Route path="/yeu-cau" element={<MarketplacePage/>}/><Route path="/yeu-cau-cua-toi" element={<MyRequestsPage/>}/><Route path="/chia-se" element={<SharingBoardPage/>}/><Route path="/chia-se-cua-toi" element={<MySharingPage/>}/><Route path="/dien-dan" element={<ForumPage/>}/><Route path="/server" element={<SchoolServersPage/>}/><Route path="/tin-nhan" element={<MessagesPage/>}/><Route path="/phien" element={<SessionsPage/>}/><Route path="/vi" element={<WalletPage/>}/><Route path="/tai-khoan" element={<AccountPage/>}/><Route path="/quan-tri" element={<AdminPage/>}/><Route path="/peers" element={<PeersPage/>}/><Route path="/dang-yeu-cau" element={<CreateRequestPage/>}/><Route path="/cach-hoat-dong" element={<HomePage focusHow/>}/><Route path="/login" element={<LoginPage/>}/><Route path="/register" element={<RegisterPage/>}/><Route path="*" element={<HomePage/>}/>
</Routes></main><Footer/><AiChatbot/></div>}
